### ISSUE TITLE
Emit when BlackPortal unmounts

### ISSUE THREAD

**Issue by Andreyco** [zenyr/react-native-portal#1]
**Current behaviour**
- I unmount `BlackPortal`, but it's children are displayed in `WhitePortal` after this event.

**Expected behaviour**
- I unmount `BlackPortal`, it's children should be "removed" from `WhitePortal`

From code, I see `BlackPortal` does not emit on unmount. Would this solve the issue?

**Comment by zenyr** [comment]
Yeah indeed. I'll push an update soon!
