### ISSUE TITLE
Deprecated status

### ISSUE THREAD

**Issue by ewal** [zenyr/react-native-portal#18]
Just curious why the repo is deprecated. Are there any alternatives out there?

**Comment by bwillem** [comment]
not maintained, uses old lifecycle methods. you can roll up a pretty simple implementation with functional components

`
/// PortalProvider.tsx
import React, { useState, createContext, useContext } from "react";

const portalContext = createContext({ portals: {}, setPortal: (_p: { name: string, component: any }) => null });
export const usePortalContext = () => useContext(portalContext);

function PortalProvider({ children }) {
  const [portals, setState] = useState({});

  const setPortal = ({ name, component }) => setState(s => ({ ...s, [name]: component }));

  return (
    <portalContext.Provider value={{ portals, setPortal }}>
      {children}
    </portalContext.Provider>
  );
}

export default PortalProvider;
`

`
/// Portal.tsx
import { usePortalContext } from "./PortalProvider";
import { useEffect } from "react";

/**
 * ingests children
 */
function BlackPortal({ name, children }) {
  const { setPortal } = usePortalContext();

  useEffect(() => {
    setPortal({ name, component: children });
  }, [children]);

  return null;
}

/**
 * barfs children
 */
function WhitePortal({ name }) {
  const { portals } = usePortalContext();

  return portals[name] || null;
}

export {
  BlackPortal,
  WhitePortal,
};
`
