### ISSUE TITLE
v1.1.1 doesn't work with react-native

### ISSUE THREAD

**Issue by doomsower** [zenyr/react-native-portal#2]
I upgraded from v1.0.2 to v1.1.1 and react-native v0.46.4 app failed with red screen and error message `React is not defined`. Downgraded to v1.0.2 and everything is working again. So I guess something is wrong with rollup build?

**Comment by zenyr** [comment]
It is totally possible that I had mis-configured `package.json`. I'll tinker with that but in the meantime you can stay on 1.0.2 since it should be exactly same anyway. Only documentations and stuff was updated.

Thanks for the report!

**Comment by zenyr** [comment]
v1.1.3 should fix the issue now. TBH it is only tested on my setup so let me know if this fix was not enough for you. 😸

**Comment by doomsower** [comment]
Thank you, it works now!
