### ISSUE TITLE
does PortalProvider really need to use setState?

### ISSUE THREAD

**Issue by fmobus** [zenyr/react-native-portal#7]
Hi,

I'm considering using this library for my React Native project, because the implementation looks really simple and straightforward.

However, upon reviewing the code, I noticed that PortalProvider uses state to store the current implementation for each portal name. What worries me is that changing the state usually triggers re-renders of everything that's under it. Considering that PortalProvider would usually way up in the application component tree, this could mean triggering re-renders of the whole application, i.e. things that are not at all involved in with the relevant WhitePortal or BlackPortal.

Would it make sense to store the current implementation as a local variable bound to the PortalProvider object itself? In other words:

````
  portalSet = (name, value) => {
    const emitter = this._emitter;
    this.implementations[name] = value
    emitter && emitter.emit(name)
  };

  portalGet = name => this.implementations[name] || null
````

My understanding is that the necessary renders would still happen because we have explicit forceUpdates in WhitePortal. Shouldn't that be enough?

**Comment by zenyr** [comment]
Hey, you're right. Maybe I could move out this.state off of the provider and publish with major/minor version bump. Nice suggestion.

**Comment by doomsower** [comment]
I just face an issue described here, with portals creating infinite render loop.
Tested the PR branch in my app and it fixed the loop.

**Comment by zenyr** [comment]
Validating my TS conversion on `react-native` I forgot to cherrypick this change on the main version. and it's concise enough! You totally took over my procrastination 👍 

Closing thanks to #8
